import = ["~/.config/alacritty/themes/themes/solarized_dark.toml"]

[font]
builtin_box_drawing = true
size = 14.0

[font.bold]
family = "SauceCodePro Nerd Font"
style = "SemiBold"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = false

[scrolling]
history = 0

[shell]
args = ["-arm64", "/opt/homebrew/bin/tmux", "attach"]
program = "arch"

[window]
dynamic_padding = true
startup_mode = "Fullscreen"
