preview = true

[lint]
fixable = ["ALL"]
extend-safe-fixes = ["ALL"]
select = [
  "A",   # flake8-builtins
  "AIR", # Airflow
  # "ANN", # flake8-annotations
  "ARG",   # flake8-unused-arguments
  "ASYNC", # flake8-async
  "B",     # flake8-bugbear
  # "BLE", # flake8-blind-except
  "C4",  # flake8-comprehensions
  "C90", # mccabe
  "COM", # flake8-commas
  # "CPY", # flake8-copyright
  "D",  # pydocstyle
  "DJ", # flake8-django
  # "DTZ", # flake8-datetimez
  "E",
  "W",   # pycodestyle
  "EM",  # flake8-errmsg
  "ERA", # eradicate
  "EXE", # flake8-executable
  "F",   # Pyflakes
  # "FA", # flake8-future-annotations
  "FBT",  # flake8-boolean-trap
  "FIX",  # flake8-fixme
  "FLY",  # flynt
  "FURB", # refurb
  "G",    # flake8-logging-format
  "I",    # isort
  "ICN",  # flake8-import-conventions
  # "INP", # flake8-no-pep420
  "INT",  # flake8-gettext
  "ISC",  # flake8-implicit-str-concat
  "LOG",  # flake8-logging
  "N",    # pep8-naming
  "NPY",  # NumPy-specific rules
  "PD",   # pandas-vet
  "PERF", # Perflint
  "PGH",  # pygrep-hooks
  "PIE",  # flake8-pie
  "PL",   # Pylint
  "PT",   # flake8-pytest-style
  # "PTH",  # flake8-use-pathlib
  "PYI",  # flake8-pyi
  # "Q", # flake8-quotes
  "RET",  # flake8-return
  "RSE",  # flake8-raise
  "RUF",  # Ruff-specific rules
  "S",    # flake8-bandit
  "SIM",  # flake8-simplify
  "SLF",  # flake8-self
  "SLOT", # flake8-slots
  "T10",  # flake8-debugger
  # "T20", # flake8-print
  "TCH",  # flake8-type-checking
  "TD",   # flake8-todos
  "TID",  # flake8-tidy-imports
  "TRIO", # flake8-trio
  "TRY",  # tryceratops
  "UP",   # pyupgrade
  "YTT",  # flake8-2020
]
ignore = [
  # Trailing comma missing
  "COM812",
  # Missing docstrings
  "D10",
  # Possible SQL injection vector through string-based query construction
  "S608",
]

[lint.per-file-ignores]
# Ignore `E402` (import violations) in all `__init__.py` files
"__init__.py" = ["E402"]
# Ignore `S101` (use of assert) in all test files
"tests/**/*.py" = ["S101"]

[lint.isort]
# Use a single line between direct and from import.
# lines-between-types = 1
